
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attacke
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: attacke.dhbw.schoeppi5.de
      http:
        paths:
          - backend:
              service:
                name: to-do-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
